### PR TITLE
Modify "ExplainSatisfies" to return the list of BinaryIndex objects that could satisfy the given relation

### PR DESCRIPTION
**Pull request by tianon**
This makes it possible to not only parse the possi, but also do meaningful things with the satisfied results (like install the matching versions, for example :smiling_imp:).

### CODE REVIEW

**Comment by tianon** [comment]
I'm not totally sold that this is the _best_ way to handle this (ie, what level preferences and pinning might connect into this whole process), but it at least does work today. :+1:

**Comment by tianon** [comment]
Oh, this also doesn't handle fun stuff like:

```
               golang (>= 2:1.2-3~),
               golang (>= 2:1.2.1-2~) | golang (<< 2:1.2.1~),
               golang (>= 2:1.3-4~) | golang (= 2:1.3-1) | golang (<< 2:1.3~),
```

**Comment by tianon** [comment]
That's a separate issue though.

**Comment by tianon** [comment]
In typing up the details of that issue, I realize it's not separate at all, and only matters if this PR merges, because this PR is interested in answering a different question than the existing code.

The existing code answers the question "Do I have deps to satisfy XYZ, and if not, why not?"  This much is easy -- in the above case, if `golang=1.3-2` is the only thing available, the first relation is satisfied, the second is satisfied, but the third is not (and the reason not is the dep itself -- pretty easy to read).

In this PR, what I'm trying to answer is "_How_ do I satisfy XYZ (which packages, exactly)?", which is more nuanced. :disappointed:

**Comment by tianon** [comment]
Basically, to answer the question I'm really after, we need something that takes this PR and uses it to find the first permutation of ALL the actual satisfying package lists `possi` that can work (ie, only one particular version of each binary package).

**Comment by tianon** [comment]
Also, I'm not sure how this code currently handle deps like `golang (>= 1:1.4~) | gccgo-5` (multiple packages in a single clause).  I suppose I probably need to read more into how `GetPossibilities` works :innocent:.

**Comment by tianon** [comment]
(Incidentally, this PR as-is is essentially how pbuilder's "classic" dependency resolver works.)

**Comment by tianon** [comment]
Here's an example of what I'm building with this:

``` Dockerfile
FROM debian:unstable
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential=12.1 \
        debhelper=9.20150628 \
        bison=2:3.0.2.dfsg-2 \
        ed=1.10-2 \
        mawk=1.3.3-17 \
        perl=5.20.2-6 \
        netbase=5.3 \
        golang=2:1.4.2-3 \
        po-debconf=1.0.18 \
    && rm -rf /var/lib/apt/lists/*
```

**Comment by paultag** [comment]
Hurm, so I like this, but I think it's starting to get unclean. I'll merge this, then we should start breaking this out a bit more

**Pull request merged**
